### ISSUE TITLE
Configuration schema - unable to configure properly

### ISSUE THREAD

**Issue by mpromny** [Kong/kong-python-pdk#22]
Hi,

I’m struggling with configuration schema in custom python plugin. Maybe you know, what i am doing wrong. All suggestions are welcome.

Please find below the details:

Plugin configuration:
```
#!/usr/bin/python3
import kong_pdk.pdk.kong as kong

Schema = (
    {"message": {"type": "string"},"var1": {"type": "string"}}
)

class Plugin(object):

    def __init__(self, config):
        self.config = config

    def access(self, kong: kong):
        message = "defaultMsg"
        if 'message' in self.config:
            message = self.config['message']


        variable_1 = "defaultVariable"
        if 'var1' in self.config:
            variable_1 = self.config['var1']

        kong.log.err("Message set in config: ", str(message))
        kong.log.err("Variable set in config: ", str(variable_1))


if __name__ == "__main__":
    from kong_pdk.cli import start_dedicated_server
    start_dedicated_server("py-hello", Plugin, version, priority)
```

Kong configuration:

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: py-hello
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
  config:
    message: "myMessage"
    var1: "myVariable"
plugin: py-hello

```

Unfortunately, it doesn’t work.

Thank you in advance,
Mateusz

**Comment by fffonion** [comment]
Hi @mpromny you will need to activate the python plugin server in kong configuration. Please see
https://docs.konghq.com/gateway-oss/2.5.x/external-plugins/#example-configuration-2 as reference.
In k8s, kong config are passed as env variable for the pod.

**Comment by mpromny** [comment]
Hi @fffonion,

Maybe I was slightly inaccurate in the description of my issue.

- plugin has been deployed and it's working 
- it has been started as microservice (each plugin as separated server)

Issue:
- I cannot correctly configure(activate) plugin in kong to set message field (neither declarative nor db-less config works)

DB-Less approach:
```
      - name: py-hello
        config:
          message: "testConfigSet"
or
      - name: py-hello
        config:
          message: 
            - "testConfigSet"
``` 
Error:
```
2021/08/04 18:08:26 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:512: error parsing declarative config file /kong_dbless/kong.yml:
in 'plugins':
- in entry 2 of 'plugins':
in 'config':
in 'message': unknown field
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/kong/init.lua:512: in function 'init'
init_by_lua:3: in main chunk
```

When I remove config part from plugin configuration in kong:
```
        config:
          message: "testConfigSet"
```
plugin is working and I can log that message has been set inside plugin:
```
DEBG - [23:36:31] rpc: #12 return: {'Data': {'Method': 'kong.log.err', 'Args': ('#####################', 'hello')}, 'EventId': 1}, context: ngx.timer

handled by:
        message = "hello"
        if 'message' in self.config:
            message = self.config['message']
        kong.log.err("#####################", message) 
```


Additional information:
- from plugin I don't have access to the environment variables:
```
os.environ
```
returns
```
"environ({'SHLVL': '1', 'PWD': '/'})",)}
```
